copyright = ""
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "Europe/Berlin"
timeout = "120s"
title = "Gallery"

[params]
  defaultTheme = "dark"
  description = "Example site for hugo-theme-gallery"
  title = "My Gallery"
  [params.author]
    email = "chris.boyscout@gmail.com"
    name = ""
  [params.socialIcons]
    facebook = ""
    instagram = ""
    github = ""
    youtube = ""
    email = "mailto:chris.boysscout@gmail.com"
    #website = ""
    #mastodon = ""
    #pixelfed = ""
    #mixcloud = ""
    #flickr = ""
    #500px = ""
    #whatsapp = ""
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menu]
